# Generated by Django 2.1.3 on 2019-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pageloadslogbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='static_out_top_list',
            field=models.BooleanField(default=False),
        ),
    ]
